# Generated by Django 3.1.3 on 2020-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(max_length=100)),
                ('cont0', models.CharField(default='', max_length=1000)),
                ('head1', models.CharField(max_length=100)),
                ('cont1', models.CharField(default='', max_length=1000)),
                ('head2', models.CharField(max_length=100)),
                ('cont2', models.CharField(default='', max_length=1000)),
                ('post_date', models.DateField()),
                ('thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
    ]
