# Generated by Django 3.1.3 on 2020-11-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField(default=0)),
                ('catagery', models.CharField(default='', max_length=50)),
                ('sub_category', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=200)),
                ('prod_date', models.DateField()),
                ('prod_image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
