# Generated by Django 3.1.3 on 2020-11-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='catagery',
            new_name='category',
        ),
    ]
